### ISSUE TITLE
Adicionar / ADD Outline TTS

### ISSUE THREAD

**Issue by joaogomesnoob** [taxpayer/outliner-extension#3]
Oi Rodrigo!
Pelo que estou vendo parece bastante simples de adicionar
O redirect já faz todo o trabalho pelo que entendi é um 302
VLW :)
---

Hello Rodrigo!
From what I'm seeing it looks pretty simple to add
The redirect already does all the work from what I understand it's a 302
Thanks :)
---
Original: https://www1.folha.uol.com.br/poder/2022/04/presidenciaveis-veem-golpe-de-lira-ao-encampar-plano-do-semipresidencialismo.shtml
Redirect: https://outlinetts.com/article/https/www1.folha.uol.com.br/poder/2022/04/presidenciaveis-veem-golpe-de-lira-ao-encampar-plano-do-semipresidencialismo.shtml
Artigo: https://outlinetts.com/article/page/folha/poder/2022/04/presidenciaveis-veem-golpe-de-lira-ao-encampar-plano-do-semipresidencialismo.shtml

**Comment by taxpayer** [comment]
Oi @joaogomesnoob, tudo bem?

Obrigado pelo código. Testei aqui em algumas páginas e a lógica funcionou exatamente conforme você descreveu. Aproveitando o tópico, queria levantar 2 questões sobre o OutlineTTS, que venho estudando desde o momento que entendi que o Outline original tinha ido mesmo pro saco:

1. Se você pegar uma página que ainda não esteja no cache deles, o processo de geração da página está demorando cerca de 20s entre chamar a URL do redirect e aparecer alguma coisa na página. É muito tempo, fico meio preocupado disso virar um problema para os usuários. Depois que a página é renderizada uma primeira vez, aí ele abre sempre bastante rápido.

2. Você já parou para avaliar o tanto de coisas são carregadas via JS na página renderizada? Também fiquei com o pé atrás em relação a isso. O Outline original tinha um footprint bem menor e o 12ft.io, que coloquei atualmente substituindo também, praticamente só o Google Tag.

Eu quero colocar um menu na próxima atualização para o usuário escolher qual serviço quer usar e vou implementar o OutlineTTS, mas queria saber a sua opinião e das pessoas sobre esses 2 pontos aí.

Grande abraço,
R.

**Comment by taxpayer** [comment]
@joaogomesnoob Obrigado pelas opiniões! Vou começar a implementar o lance de escolher diferentes serviços e vou incluir o OutlineTTS lá.

Abraço,
R.
