### ISSUE TITLE
More sites like Outline TTS to add :)

### ISSUE THREAD

**Issue by joaogomesnoob** [taxpayer/outliner-extension#4]
Hi Rodrigo how you doing, I found with a bit of Googling some more sites like Outline TTS so here will be more 5 alternatives
--
Eae Rodrigo como vc vai! Encontrei Googlando mais alguns sites exatamente como o Outline TTS então aqui deixo mais 5 alternativas
--
Abraço :)
[ttspress.com](https://ttspress.com/)
[newsreader.info](https://newsreader.info/)
[readertts.com](https://readertts.com/)
[easyreader.org](https://easyreader.org/)
[newsvoice.info](https://newsvoice.info/)

**Comment by joaogomesnoob** [comment]
Parece que estes sites funcionam exatamente igual ao Outline TTS então a forma de programar seu plugin deve ser igual ao Outline TTS, depois me diga o que achou :)

**Comment by taxpayer** [comment]
Fala @joaogomesnoob.

Dei uma olhada nos sites e, sinceramente, só fizeram aumentar uma certa desconfiança que tenho nesse OutlineTTS. Tdoos esses sites que você indicou são basicamente a mesma coisa com outros domínios e uma interface um pouco modificada. O JS por trás é exatamente o mesmo e o registro de DNS deles idem, apontando para mesmo servidores, mesmo serviço de registro (Namecheap) e datas de registro perto uma das outras.

Eu entendo que qualquer serviço precisas de dinheiro para se manter, mas há diversas maneiras de se tentar isso. Multiplicar um site com outros nomes dando a entender que são coisas distintas está entre o que não considero decente de se fazer para conseguir esse objetivo.

Agradeço pela lista, não vou incluir esses sites na extensão mas ajudou a clarear ainda mais essa desconfiança que ainda tenho do OutlineTTS. Vou continuar monitorando, mas se entender que o objetivo dele parece ser algum tipo de scam a longo prazo, eu tiro ele lá da extensão em 2 tempos.

Grande abraço,
Rodrigo

**Comment by joaogomesnoob** [comment]
Eae @taxpayer 

Entendo sua desconfiança sobre esses serviço porém se ver o registro whois deste easyreader tem data de 2021, talvez os desenvolvedores por detrás estejam a se relançar no mercado, eu sinceramente não acho a ideia ruim como você acha, porém deixo uma dica, que tal você passar a parte de redirecionamento por um servidor sobre seu controlo assim evita ter de reenviar para aprovação toda a hora em caso de problema,
Sobre os JS é meramente anúncios não vi nada de especial mesmo qualquer adblock trava esses JS e o site continua funcionando igual... então assim seu ponto sobre ser scam realmente discordo completamente mas compreendo suas preocupações.
Afirmo o melhor serviço que usei nos últimos tempos desde que o outline original saiu do ar, é uma pena você não querer adicionar... aquele ttspress achei bom demais!

Abraços,
João

**Comment by taxpayer** [comment]
Fala @joaogomesnoob!

Pelo contrário! Eu *adicionei* o OutlineTTS, especialmente pelo seu primeiro feedback... :-D Eu havia mandado a extensão com a nova versão 3.0, com diversas novidades, para aprovação na quinta passada, somente hoje mais cedo é que foi aprovada e o OutlineTTS está lá disponível, você pode configurá-lo como o seu serviço padrão... :-)

Só realmente não estou 100% com ele, mas vou mentâ-lo até entender que há algum problema. 

Se puder, dê uma avaliada na nova versão e me dê seu feedback. E mais uma vez obrigado pela mensagem sobre a chamada do OulineTTS, ajudou bastante na implementação.

Abraço,
Rodrigo

**Comment by joaogomesnoob** [comment]
@taxpayer Legal farei isso! depois pense se é possível adicionar aquele ttspress deixo ao seu critério (amei aquele night mode kkkk)

A propósito você já tentou falar com o desenvolvedor deste Outline TTS? no whois tem aqueles emails protegidos geralmente o desenvolvedor recebe o email, ai você tira suas duvidas.

Abraços,
João

**Comment by taxpayer** [comment]
@joaogomesnoob Já sim e foi um dos motivos pelo qual achei estranho. Eu procurei em todas as páginas disponíveis lá e só achei um único email, dmca@outlinetts.com, em https://outlinetts.com/about.

Eu mandei uma mensagem para esse email, mas ele retornou por caixa postal não configurada, como se o registro MX não tivesse sido configurado. Caso tivesse conseguido falar teria sido legal.

Abraço,
Rodrigo

**Comment by projectify** [comment]
@taxpayer Tenta esse e-mail: 8dc03c6888c549eb9abecacd3e0c4b99.protect@withheldforprivacy.com
Que é o que ta no whois!

Abraços,
João

**Comment by joaogomesnoob** [comment]
@taxpayer Tenta esse email: 8dc03c6888c549eb9abecacd3e0c4b99.protect@withheldforprivacy.com

É o que retorna para mim no whois vê se te ajuda,

Abraços,
João

**Comment by vonDubenshire** [comment]
Hi @taxpayer, I was looking through some of the Reddit and YCombinator News pages and found your extension. 

Additionally, this website is a great Reader Mode\clean link view, and actually worked with an Economist and NYT link that usually are blocked.

https://www.darkread.io/

I don't love Dark Mode all the time but maybe you can work with the developer, he appears active on Twitter.

**Comment by taxpayer** [comment]
Hey @vonDubenshire, sorry for the late reply, but things got busy in the meantime.

Today Google published version 3.2 of the extension, which includes Darkread as an available reading service. Thank you for the tip, I didn't know it yet and it worked very well for the websites I usually read (and I'm a fan of dark-theme as well 😉)

I'm closing this now.

Thanks,
Rod

**Comment by vonDubenshire** [comment]
> Hey @vonDubenshire, sorry for the late reply, but things got busy in the meantime.
> 
> Today Google published version 3.2 of the extension, which includes Darkread as an available reading service. Thank you for the tip, I didn't know it yet and it worked very well for the websites I usually read (and I'm a fan of dark-theme as well 😉)
> 
> I'm closing this now.
> 
> Thanks, Rod

I just saw this, thanks!
