### ISSUE TITLE
clicking extension button doesn't redirect

### ISSUE THREAD

**Issue by a-woo** [taxpayer/outliner-extension#5]
When I click the extension button, it only pulls up the settings menu with "Available Services", etc. and doesn't redirect the active tab URL anywhere.

**Comment by taxpayer** [comment]
Hey @a-woo, in the last version I had to introduce a menu to set options, like the service you want to use, especially after the old Outline shutdown. So, I had to replace the previous action to redirect the current page to open the menu. You can use a context-menu (right-click) anywhere on a page to show the action **Open this page on 12ft.io/OutlineTTS** or over a link to show the action **Open this link on 12ft.io/OutlineTTS**. Check the images below.

(right-click anywhere on page)
![image](https://user-images.githubusercontent.com/9285710/165169570-ff4ad7c8-8b23-44e3-9f7d-1510a2328d55.png)

(right-click on a link)
![image](https://user-images.githubusercontent.com/9285710/165169651-adcc24d4-d918-4b28-8484-f3745f322f82.png)

Hope that helps!

Cheers,
Rod

**Comment by a-woo** [comment]
I see it now, thanks. Sorry I didn't realize it moved to a context menu.
